---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/api
    - /bin/cp -R server/* $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH